### ISSUE TITLE
data

### ISSUE THREAD

**Issue by asd52303** [JinmingWang/TrajectoryDiffusion#1]
do you know about the difference between original trajectory data and the data like gps_20161101.pt . How do you get the data like gps_20161101.pt ?

**Comment by JinmingWang** [comment]
Hello, I have uploaded the data preprocess code, it is implemented in c++, with libtorch/pytorch and openmp.

But iin case if you want to implement a python version, it is easy, just following these steps:
1. Get Didi dataset, there will be many files, named with format "gps_YYYYMMDD", for example: "gps_20161102".
2. Open and parse each file to obtain corresponding gps_YYYYMMDD.pt
2.1. Initialize an empty container to store order - trajectory points
2.2. Iterate over each line, parse the line, they are in format "driver_id,order_id,time,longitude,latitude", for example: "5a4e6de1010eab8f8857e4091f1d11bc,4966fa21f6acf3d798dbdb4dba2713fe,1479266019,108.91272,34.21812"
2.3. If the order_id does not exist, add it to container and add its first trajectory point in (time, lng, lat) format
2.4. If the order_id exists, append point (time, lng, lat) to trajectory
2.5. Save all orders as .pkl file

The final data in .pkl file appears like: (Note this is the expected output format of c++ processing code, since this implementation does not use order_id and driver_id, the order of the first two does not matter)
[
    (order_id, dirver_id, lon_lat_tensor, time_tensor),
    (order_id, driver_id, lon_lat_tensor, time_tensor),
    ...
]

**Comment by asd52303** [comment]
Thank you for your kind and detailed answer. And I have another question: Have you ever run the original code of DiffTraj https://github.com/Yasoz/DiffTraj ? I was trying to run this code but I do not know about the format of input data, I would apprieciate if you could tell me how to prepare the data for the original code of DiffTraj.

**Comment by JinmingWang** [comment]
> Thank you for your kind and detailed answer. And I have another question: Have you ever run the original code of DiffTraj https://github.com/Yasoz/DiffTraj ? I was trying to run this code but I do not know about the format of input data, I would apprieciate if you could tell me how to prepare the data for the original code of DiffTraj.

I pulled their original code and run the provided .ipynb demo, I think some .npy files are provided, which store the input data. But they are raw arrays and tensors, I had difficulty figuring out what the numbers mean (especially the context data and embedding vectors). I constructed my own context & embedding & condition part, and tested it, I found it is actually easy to reach the proposed performance, if you provide a few more context, the model can even be a little bit better than the proposed one.

**Comment by asd52303** [comment]
You just run the .ipynb demo? Have you ever run their main.py file and just train the model with your own trajectory dataset? If you have, what is the format of trajectory data (I mean the file they load in line 45 of file main.py) should be?   And another question is what is the meaning of each column in heads.npy in their original code and do you know how to calculate them if I have my own dataset? I would appreciate if you could answer the questions above.

**Comment by JinmingWang** [comment]
> You just run the .ipynb demo? Have you ever run their main.py file and just train the model with your own trajectory dataset? If you have, what is the format of trajectory data (I mean the file they load in line 45 of file main.py) should be? And another question is what is the meaning of each column in heads.npy in their original code and do you know how to calculate them if I have my own dataset? I would appreciate if you could answer the questions above.

I did not run their training code, because I do not know the meaning of each column. 😭

**Comment by JinmingWang** [comment]
> You just run the .ipynb demo? Have you ever run their main.py file and just train the model with your own trajectory dataset? If you have, what is the format of trajectory data (I mean the file they load in line 45 of file main.py) should be? And another question is what is the meaning of each column in heads.npy in their original code and do you know how to calculate them if I have my own dataset? I would appreciate if you could answer the questions above.

😭 😭 😭

**Comment by asd52303** [comment]
So did you train your own model in another way? Since I want to do baseline experiment in urgent, Can you teach me how to train a new model using our own trajectory data and to generate the trajectory?

**Comment by JinmingWang** [comment]
> So did you train your own model in another way? Since I want to do baseline experiment in urgent, Can you teach me how to train a new model using our own trajectory data and to generate the trajectory?

I have sent an email to you, could you please check you QQ-mail box?
